# This is a basic workflow to help you get started with Actions

name: CI Workflow

# Controls when the workflow will run
on: workflow_dispatch
  # Triggers the workflow on push or pull request events but only for the "dev" branch
  # push:
  #   branches: [ "dev" ]
  # pull_request:
  #   branches: [ "dev" ]

  # Allows you to run this workflow manually from the Actions tab
  # workflow_dispatch: workflow_dispatch

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  first-job:
    runs-on: ubuntu-latest
        # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
          # Runs a single command using the runners shell
      - name: Print greeting
        run: echo "Hello World!"
      - name: Print goodbye
        run: echo "Done - goodbye!"
    
  # This workflow contains a single job called "build"
  # build:
  #   # The type of runner that the job will run on
  #   runs-on: ubuntu-latest


      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      # - uses: actions/checkout@v4


      # # Runs a set of commands using the runners shell
      # - name: Run a multi-line script
      #   run: |
      #     echo Add other actions to build,
      #     echo test, and deploy your project.
